services:
  - type: web
    name: vos-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
    preDeployCommand: apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev 